name: myenv
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - gymnasium
  - scikit-image
  - setproctitle
  - matplotlib
  - scikit-learn
  - tqdm
