name: myenv
channels:
  - nvidia        # Required for pytorch-cuda
  - pytorch       # Required for latest GPU PyTorch
  - conda-forge
  - defaults
dependencies:
  - python
  - gymnasium
  - scikit-image
  - setproctitle
  - pytorch
  - pytorch-cuda=12.1
  - wandb
  - matplotlib
  - scikit-learn
  - tqdm
